# Base configs
baseurl: ""
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Sebastian Contreras"
subtitle: "Snapping moments, one day at a time."
author: "Sebastian Contreras"
header:
 title: "Photography"
 subtitle: "by Sebastian Contreras"
footer:
 name: "Hey, I'm Sebastian!"
 bio: "Civil engineer, music lover, and now chasing light & stories with my camera. Based in Chile. Welcome to my casual corner of the internet."
 github: "Curious about how this site works? <a href=\"https://github.com/sebastiancontrerasa/photography\">Fork this on GitHub</a> and make it yours.;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  X: "https://x.com/AracenaSebasti"
  instagram: "https://www.instagram.com/contrerasa.93"
  linkedin: "https://www.linkedin.com/in/sebastian-contreras-aracena-a41a61155"
  github: "https://github.com/sebastiancontrerasa"
